services:            
    mdn_admin.grid.type.user:
        class: MDN\AdminBundle\Grid\Type\UserType
        arguments: ['@service_container']
        
    mdn_admin.grid.type.role:
        class: MDN\AdminBundle\Grid\Type\RoleType
        arguments: ['@service_container']
        
    mdn_admin.grid.type.server:
        class: MDN\AdminBundle\Grid\Type\ServerType
        arguments: ['@service_container']